title: "Mapping the Reef: Underwater 3D Reconstruction for Coral Ecosystems"
description: Title
sitename: Mapping-the-Reef@RSS26
baseurl: "/Mapping-the-Reef-RSS26"
url: "https://alejandrofontan.github.io"

# Scholar
# ========================================================================================
scholar:
  style: apa
  locale: en
  sort_by: year, month
  order: descending
  source: ./
  bibliography: resources.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: false
  query: "@*"

plugins:
  - jekyll/scholar

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
  - resources.bib
